In [1]:
import pandas as pd
print(pd.__version__)

3.0.5

In [2]:
import pandas as pd

scores = pd.Series([85, 92, 78])
print(type(scores))
print(scores)

<class 'pandas.Series'>
0    85
1    92
2    78
dtype: int64

In [3]:

df = pd.DataFrame({
    "name": ["민수", "지영", "서준"],
    "score": [85, 92, 78],
})

print(df)

  name  score
0   민수     85
1   지영     92
2   서준     78

In [4]:
df.info(
)

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   score   3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 180.0 bytes

In [5]:
df.describe()

       score
count    3.0
mean    85.0
std      7.0
min     78.0
25%     81.5
50%     85.0
75%     88.5
max     92.0

In [6]:
df.shape

(3, 2)

In [8]:
df.head()

  name  score
0   민수     85
1   지영     92
2   서준     78

In [10]:
df.columns[1]

'score'

In [ ]:
a = df["score"]
print(type(a))
print(a)

<class 'pandas.Series'>
0    85
1    92
2    78
Name: score, dtype: int64

In [12]:
b = df[["score"]]
print(type(b))
print(b)

<class 'pandas.DataFrame'>
   score
0     85
1     92
2     78

In [15]:
# data/chapter21/store_sales.csv
# https://github.com/GilbertMoon/ai-python-basics-reader-resources/blob/main/data/chapter21/store_sales.csv

import pandas as pd

df_sales = pd.read_csv("https://raw.githubusercontent.com/GilbertMoon/ai-python-basics-reader-resources/refs/heads/main/data/chapter21/store_sales.csv")

print(df_sales)

         date product category  price  quantity channel city
0  2026-08-01     키보드     주변기기  45000         2     온라인   서울
1  2026-08-02     마우스     주변기기  25000         3    오프라인   부산
2  2026-08-03      웹캠       영상  65000         1     온라인   서울
3  2026-08-04    모니터암     사무기기  85000         2     온라인   인천
4  2026-08-05   USB허브     주변기기  32000         4    오프라인   대전
5  2026-08-06     헤드셋      오디오  78000         1     온라인   서울
6  2026-08-07  노트북거치대     사무기기  39000         2     온라인   대구
7  2026-08-08     스피커      오디오  55000         2    오프라인   부산
8  2026-08-09     마이크      오디오  92000         1     온라인   광주
9  2026-08-10     케이블     주변기기  12000         5     온라인  NaN

In [17]:
df_sales.info()
df_sales.head()
df_sales.tail()
df_sales.describe()
df_sales.isna()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      10 non-null     str
 1   product   10 non-null     str
 2   category  10 non-null     str
 3   price     10 non-null     int64
 4   quantity  10 non-null     int64
 5   channel   10 non-null     str
 6   city      9 non-null      str
dtypes: int64(2), str(5)
memory usage: 692.0 bytes

    date  product  category  price  quantity  channel   city
0  False    False     False  False     False    False  False
1  False    False     False  False     False    False  False
2  False    False     False  False     False    False  False
3  False    False     False  False     False    False  False
4  False    False     False  False     False    False  False
5  False    False     False  False     False    False  False
6  False    False     False  False     False    False  False
7  False    False     False  False     False    False  False
8  False    False     False  False     False    False  False
9  False    False     False  False     False    False   True

In [9]:

from pathlib import Path
import pandas as pd

BASE_DIR = Path.cwd()

file_path = BASE_DIR / "store_sales.csv"

df = pd.read_csv(file_path)

df.head()

         date product category  price  quantity channel city
0  2026-08-01     키보드     주변기기  45000         2     온라인   서울
1  2026-08-02     마우스     주변기기  25000         3    오프라인   부산
2  2026-08-03      웹캠       영상  65000         1     온라인   서울
3  2026-08-04    모니터암     사무기기  85000         2     온라인   인천
4  2026-08-05   USB허브     주변기기  32000         4    오프라인   대전

In [10]:
print(df.head())
print(df.tail())
print(df.shape)
print(df.columns)
print(df.dtypes)
df.info()
print(df.isna().sum())

         date product category  price  quantity channel city
0  2026-08-01     키보드     주변기기  45000         2     온라인   서울
1  2026-08-02     마우스     주변기기  25000         3    오프라인   부산
2  2026-08-03      웹캠       영상  65000         1     온라인   서울
3  2026-08-04    모니터암     사무기기  85000         2     온라인   인천
4  2026-08-05   USB허브     주변기기  32000         4    오프라인   대전
         date product category  price  quantity channel city
5  2026-08-06     헤드셋      오디오  78000         1     온라인   서울
6  2026-08-07  노트북거치대     사무기기  39000         2     온라인   대구
7  2026-08-08     스피커      오디오  55000         2    오프라인   부산
8  2026-08-09     마이크      오디오  92000         1     온라인   광주
9  2026-08-10     케이블     주변기기  12000         5     온라인  NaN
(10, 7)
Index(['date', 'product', 'category', 'price', 'quantity', 'channel', 'city'], dtype='str')
date          str
product       str
category      str
price       int64
quantity    int64
channel       str
city          str
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      10 non-null     str
 1   product   10 non-null     str
 2   category  10 non-null     str
 3   price     10 non-null     int64
 4   quantity  10 non-null     int64
 5   channel   10 non-null     str
 6   city      9 non-null      str
dtypes: int64(2), str(5)
memory usage: 692.0 bytes
date        0
product     0
category    0
price       0
quantity    0
channel     0
city        1
dtype: int64

# mission01

In [19]:
print(f"행과 열수: {df.shape}")
print(f"열 이름: {df.columns}")
print(f"price자료형: {df.price.dtypes}")
print(f"quantity자료형: {df.quantity.dtypes}")
print(f"city 결측값: {df.city.isna().sum()}")

행과 열수: (10, 7)
열 이름: Index(['date', 'product', 'category', 'price', 'quantity', 'channel', 'city'], dtype='str')
price자료형: int64
quantity자료형: int64
city 결측값: 1

In [21]:
products = df["product"]
print(products)
print(type(df["product"]))

0       키보드
1       마우스
2        웹캠
3      모니터암
4     USB허브
5       헤드셋
6    노트북거치대
7       스피커
8       마이크
9       케이블
Name: product, dtype: str
<class 'pandas.Series'>

In [22]:

selected = df[["product", "price", "quantity"]]
print(selected.head())

  product  price  quantity
0     키보드  45000         2
1     마우스  25000         3
2      웹캠  65000         1
3    모니터암  85000         2
4   USB허브  32000         4

In [24]:
print(df["price"])

0    45000
1    25000
2    65000
3    85000
4    32000
5    78000
6    39000
7    55000
8    92000
9    12000
Name: price, dtype: int64

In [25]:
print(df["category"])

0    주변기기
1    주변기기
2      영상
3    사무기기
4    주변기기
5     오디오
6    사무기기
7     오디오
8     오디오
9    주변기기
Name: category, dtype: str

In [26]:
print(df[["product", "channel", "city"]].head())

  product channel city
0     키보드     온라인   서울
1     마우스    오프라인   부산
2      웹캠     온라인   서울
3    모니터암     온라인   인천
4   USB허브    오프라인   대전

In [27]:
condition = df["price"] >= 50000
print(condition)

0    False
1    False
2     True
3     True
4    False
5     True
6    False
7     True
8     True
9    False
Name: price, dtype: bool

In [28]:
expensive = df[df["price"] >= 50000]
print(expensive)

         date product category  price  quantity channel city
2  2026-08-03      웹캠       영상  65000         1     온라인   서울
3  2026-08-04    모니터암     사무기기  85000         2     온라인   인천
5  2026-08-06     헤드셋      오디오  78000         1     온라인   서울
7  2026-08-08     스피커      오디오  55000         2    오프라인   부산
8  2026-08-09     마이크      오디오  92000         1     온라인   광주

In [29]:
online_expensive = df[
    (df["price"] >= 50000) & (df["channel"] == "온라인")
]

print(online_expensive)

         date product category  price  quantity channel city
2  2026-08-03      웹캠       영상  65000         1     온라인   서울
3  2026-08-04    모니터암     사무기기  85000         2     온라인   인천
5  2026-08-06     헤드셋      오디오  78000         1     온라인   서울
8  2026-08-09     마이크      오디오  92000         1     온라인   광주

In [30]:
print(df["price"].mean())
print(df["price"].min())
print(df["price"].max())
print(df["quantity"].sum())

52800.0
12000
92000
23

In [31]:
print(df[["price", "quantity"]].describe())

              price   quantity
count     10.000000  10.000000
mean   52800.000000   2.300000
std    26840.268255   1.337494
min    12000.000000   1.000000
25%    33750.000000   1.250000
50%    50000.000000   2.000000
75%    74750.000000   2.750000
max    92000.000000   5.000000

In [32]:
print(df.isna().sum())

date        0
product     0
category    0
price       0
quantity    0
channel     0
city        1
dtype: int64

# mission 02

In [44]:
from pathlib import Path
import pandas as pd
BASE_DIR = Path.cwd()
file_path = BASE_DIR/"store_sales.csv"

print("현재 위치:", BASE_DIR)
print("찾는 파일:", file_path)
print("파일 존재:", file_path.exists())

df = pd.read_csv(file_path)



print("=== 앞부분 ===")

print(df.head())

print("=== 크기 ===")

print(df.shape)

print("=== 열 이름 ===")

print(df.columns)

print("=== 자료형 ===")

print(df.dtypes)

print("=== 기초 통계 ===")

print(df[["price", "quantity"]].describe())

print("=== 결측값 ===")

print(df.isna().sum())

현재 위치: c:\dev\python-basics\chapter21
찾는 파일: c:\dev\python-basics\chapter21\store_sales.csv
파일 존재: True
=== 앞부분 ===
         date product category  price  quantity channel city
0  2026-08-01     키보드     주변기기  45000         2     온라인   서울
1  2026-08-02     마우스     주변기기  25000         3    오프라인   부산
2  2026-08-03      웹캠       영상  65000         1     온라인   서울
3  2026-08-04    모니터암     사무기기  85000         2     온라인   인천
4  2026-08-05   USB허브     주변기기  32000         4    오프라인   대전
=== 크기 ===
(10, 7)
=== 열 이름 ===
Index(['date', 'product', 'category', 'price', 'quantity', 'channel', 'city'], dtype='str')
=== 자료형 ===
date          str
product       str
category      str
price       int64
quantity    int64
channel       str
city          str
dtype: object
=== 기초 통계 ===
              price   quantity
count     10.000000  10.000000
mean   52800.000000   2.300000
std    26840.268255   1.337494
min    12000.000000   1.000000
25%    33750.000000   1.250000
50%    50000.000000   2.000000
75%    74750.000000   2.750000
max    92000.000000   5.000000
=== 결측값 ===
date        0
product     0
category    0
price       0
quantity    0
channel     0
city        1
dtype: int64